QT -= gui

CONFIG += c++11 console
CONFIG -= app_bundle

DEFINES  += QT_DEPRECATED_WARNINGS
DEFINES  += QT_DISABLE_DEPRECATED_BEFORE=0x060000
DEFINES  += QT_NO_CAST_FROM_ASCII
DEFINES  += QT_NO_CAST_TO_ASCII

SOURCES += main.cpp
